import fs from "fs";
import path from "path";
import { logInfo, logWarn } from "../utils/logger.js";

const HOOK_MARKER = "# CodeProof pre-commit hook";

function getHookPath(gitRoot) {
  return path.join(gitRoot, ".git", "hooks", "pre-commit");
}

function getHookBlock() {
  return [
    "",
    HOOK_MARKER,
    "codeproof run",
    "RESULT=$?",
    "if [ $RESULT -ne 0 ]; then",
    "  echo \"CodeProof checks failed. Commit blocked.\"",
    "  exit $RESULT",
    "fi",
    ""
  ].join("\n");
}

export function installPreCommitHook(gitRoot) {
  const hookPath = getHookPath(gitRoot);
  const hookDir = path.dirname(hookPath);

  if (!fs.existsSync(hookDir)) {
    fs.mkdirSync(hookDir, { recursive: true });
  }

  if (!fs.existsSync(hookPath)) {
    // Use a POSIX shell hook for cross-platform Git compatibility (Git Bash on Windows).
    const content = [
      "#!/bin/sh",
      "", 
      "# Auto-generated by CodeProof",
      "codeproof run",
      "RESULT=$?",
      "if [ $RESULT -ne 0 ]; then",
      "  echo \"CodeProof checks failed. Commit blocked.\"",
      "  exit $RESULT",
      "fi",
      ""
    ].join("\n");
    fs.writeFileSync(hookPath, content, "utf8");
    logInfo("Created new pre-commit hook.");
  } else {
    const existing = fs.readFileSync(hookPath, "utf8");
    if (existing.includes("codeproof run") || existing.includes(HOOK_MARKER)) {
      logWarn("Pre-commit hook already references CodeProof. Skipping append.");
    } else {
      // Append instead of overwrite to avoid breaking existing hook logic.
      fs.appendFileSync(hookPath, getHookBlock(), "utf8");
      logInfo("Appended CodeProof to existing pre-commit hook.");
    }
  }

  try {
    fs.chmodSync(hookPath, 0o755);
  } catch {
    // Best-effort: Windows may not honor chmod, but Git still runs hooks.
  }
}


